/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlightsFlightIdPaymentRouteImport } from './routes/flights/$flightId/payment'
import { Route as FlightsFlightIdConfirmationRouteImport } from './routes/flights/$flightId/confirmation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsFlightIdPaymentRoute = FlightsFlightIdPaymentRouteImport.update({
  id: '/flights/$flightId/payment',
  path: '/flights/$flightId/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsFlightIdConfirmationRoute =
  FlightsFlightIdConfirmationRouteImport.update({
    id: '/flights/$flightId/confirmation',
    path: '/flights/$flightId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flights/$flightId/confirmation': typeof FlightsFlightIdConfirmationRoute
  '/flights/$flightId/payment': typeof FlightsFlightIdPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flights/$flightId/confirmation': typeof FlightsFlightIdConfirmationRoute
  '/flights/$flightId/payment': typeof FlightsFlightIdPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flights/$flightId/confirmation': typeof FlightsFlightIdConfirmationRoute
  '/flights/$flightId/payment': typeof FlightsFlightIdPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flights/$flightId/confirmation'
    | '/flights/$flightId/payment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flights/$flightId/confirmation' | '/flights/$flightId/payment'
  id:
    | '__root__'
    | '/'
    | '/flights/$flightId/confirmation'
    | '/flights/$flightId/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlightsFlightIdConfirmationRoute: typeof FlightsFlightIdConfirmationRoute
  FlightsFlightIdPaymentRoute: typeof FlightsFlightIdPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$flightId/payment': {
      id: '/flights/$flightId/payment'
      path: '/flights/$flightId/payment'
      fullPath: '/flights/$flightId/payment'
      preLoaderRoute: typeof FlightsFlightIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$flightId/confirmation': {
      id: '/flights/$flightId/confirmation'
      path: '/flights/$flightId/confirmation'
      fullPath: '/flights/$flightId/confirmation'
      preLoaderRoute: typeof FlightsFlightIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlightsFlightIdConfirmationRoute: FlightsFlightIdConfirmationRoute,
  FlightsFlightIdPaymentRoute: FlightsFlightIdPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
