/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationsSearchRouteImport } from './routes/reservations/search'
import { Route as ReservationsAgentRouteImport } from './routes/reservations/agent'
import { Route as ReservationsConfirmationCodeRouteImport } from './routes/reservations/$confirmationCode'
import { Route as AdminAgentStatisticsRouteImport } from './routes/admin/agent-statistics'
import { Route as FlightsFlightIdPaymentRouteImport } from './routes/flights/$flightId/payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsSearchRoute = ReservationsSearchRouteImport.update({
  id: '/reservations/search',
  path: '/reservations/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsAgentRoute = ReservationsAgentRouteImport.update({
  id: '/reservations/agent',
  path: '/reservations/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsConfirmationCodeRoute =
  ReservationsConfirmationCodeRouteImport.update({
    id: '/reservations/$confirmationCode',
    path: '/reservations/$confirmationCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAgentStatisticsRoute = AdminAgentStatisticsRouteImport.update({
  id: '/admin/agent-statistics',
  path: '/admin/agent-statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsFlightIdPaymentRoute = FlightsFlightIdPaymentRouteImport.update({
  id: '/flights/$flightId/payment',
  path: '/flights/$flightId/payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/agent-statistics': typeof AdminAgentStatisticsRoute
  '/reservations/$confirmationCode': typeof ReservationsConfirmationCodeRoute
  '/reservations/agent': typeof ReservationsAgentRoute
  '/reservations/search': typeof ReservationsSearchRoute
  '/flights/$flightId/payment': typeof FlightsFlightIdPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/agent-statistics': typeof AdminAgentStatisticsRoute
  '/reservations/$confirmationCode': typeof ReservationsConfirmationCodeRoute
  '/reservations/agent': typeof ReservationsAgentRoute
  '/reservations/search': typeof ReservationsSearchRoute
  '/flights/$flightId/payment': typeof FlightsFlightIdPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/agent-statistics': typeof AdminAgentStatisticsRoute
  '/reservations/$confirmationCode': typeof ReservationsConfirmationCodeRoute
  '/reservations/agent': typeof ReservationsAgentRoute
  '/reservations/search': typeof ReservationsSearchRoute
  '/flights/$flightId/payment': typeof FlightsFlightIdPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/agent-statistics'
    | '/reservations/$confirmationCode'
    | '/reservations/agent'
    | '/reservations/search'
    | '/flights/$flightId/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/agent-statistics'
    | '/reservations/$confirmationCode'
    | '/reservations/agent'
    | '/reservations/search'
    | '/flights/$flightId/payment'
  id:
    | '__root__'
    | '/'
    | '/admin/agent-statistics'
    | '/reservations/$confirmationCode'
    | '/reservations/agent'
    | '/reservations/search'
    | '/flights/$flightId/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAgentStatisticsRoute: typeof AdminAgentStatisticsRoute
  ReservationsConfirmationCodeRoute: typeof ReservationsConfirmationCodeRoute
  ReservationsAgentRoute: typeof ReservationsAgentRoute
  ReservationsSearchRoute: typeof ReservationsSearchRoute
  FlightsFlightIdPaymentRoute: typeof FlightsFlightIdPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/search': {
      id: '/reservations/search'
      path: '/reservations/search'
      fullPath: '/reservations/search'
      preLoaderRoute: typeof ReservationsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/agent': {
      id: '/reservations/agent'
      path: '/reservations/agent'
      fullPath: '/reservations/agent'
      preLoaderRoute: typeof ReservationsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/$confirmationCode': {
      id: '/reservations/$confirmationCode'
      path: '/reservations/$confirmationCode'
      fullPath: '/reservations/$confirmationCode'
      preLoaderRoute: typeof ReservationsConfirmationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agent-statistics': {
      id: '/admin/agent-statistics'
      path: '/admin/agent-statistics'
      fullPath: '/admin/agent-statistics'
      preLoaderRoute: typeof AdminAgentStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$flightId/payment': {
      id: '/flights/$flightId/payment'
      path: '/flights/$flightId/payment'
      fullPath: '/flights/$flightId/payment'
      preLoaderRoute: typeof FlightsFlightIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAgentStatisticsRoute: AdminAgentStatisticsRoute,
  ReservationsConfirmationCodeRoute: ReservationsConfirmationCodeRoute,
  ReservationsAgentRoute: ReservationsAgentRoute,
  ReservationsSearchRoute: ReservationsSearchRoute,
  FlightsFlightIdPaymentRoute: FlightsFlightIdPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
